[package]
name = "ellama"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catppuccin-egui = { git = "https://github.com/zeozeozeo/catppuccin-egui.git", branch = "egui-0.27" }
eframe = "0.27"
egui_commonmark = { git = "https://github.com/lampsitter/egui_commonmark.git", features = ["better_syntax_highlighting"] }
env_logger = "0.11.3"
flowync = { version = "5.1.0", features = ["compact"] }
log = "0.4.21"
ollama-rs = { path = "../ollama-rs", features = ["rustls", "stream"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.14"
egui-modal = "0.3.6"
tts = "0.26.0"
parking_lot = "0.12.1"
